import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.scss'

export default function Layout({ children, title = 'Default title' }) {
    return (
        <div className='flex flex-col justify-center items-center'>
            <div style={{ width: '30rem', height: '40rem' }} className={`${styles.layout_body} relative bg-green-200`}>

                <Head>
                    <title>{title}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main>
                    {children}
                </main>

                <footer className={styles.footer}>
                    <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                    >
                        Powered by{' '}
                        <span className={styles.logo}>
                            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                        </span>
                    </a>
                </footer>
                
            </div>
        </div>
    );
}